# Generated by Django 5.1.2 on 2024-10-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=250)),
                ('pro_decription', models.TextField()),
                ('pro_price', models.IntegerField()),
                ('pro_image', models.ImageField(upload_to='../static/imgProducts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
